<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2015.0.2.310
*/

require_once('recaptchalib.php');
require_once('form_process.php');

$form = array(
	'subject' => 'OoTBDS Enterprise Cloud Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'admin@ootwcs.com',
		'to' => 'admin@ootwcs.com'
	),
	'recaptcha' => array(
		'private_key' => '6LfkkgITAAAAAOAkk34BXXh1D2EyqqgLK9Jg7VH6'
	),
	'fields' => array(
		'custom_U9188' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Name',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Name\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Email\' is required.',
				'format' => 'Field \'Email\' has an invalid email.'
			)
		),
		'custom_U9152' => array(
			'order' => 6,
			'type' => 'string',
			'label' => 'Company  or Organisation',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Company  or Organisation\' is required.'
			)
		),
		'custom_U9180' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Message',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Message\' is required.'
			)
		),
		'custom_U9157' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Phone',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Phone\' is required.'
			)
		),
		'recaptcha_response_field' => array(
			'order' => 8,
			'type' => 'recaptcha',
			'label' => 'Image Verification',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Image Verification\' is required.',
				'format' => 'Incorrect reCAPTCHA value.'
			)
		),
		'custom_U9184' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Storage Space Needed',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Storage Space Needed\' is required.'
			)
		),
		'custom_U9161' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Amount of Users',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Amount of Users\' is required.'
			)
		)
	)
);

process_form($form);
?>
